### ISSUE TITLE
Error in dependency declaration for mkdirp

### ISSUE THREAD

**Issue by mardiros** [npm/fstream#41]
As far as I undestand semver,

">=0.5 0" is not correct:
 https://github.com/npm/fstream/blob/master/package.json#L17

Is it a typo or did I miss something ?

**Comment by othiym23** [comment]
This is perfectly valid semver:

```
% semver -r ">=0.5 0" 0.1.0 0.4.9 0.5.0 0.5.1 0.6.0 1.0.0-pre.0 1.0.0 2.0.0
0.5.0
0.5.1
0.6.0
```

It's a little confusing because it's not obvious that a simple space (`x y`) is synonymous with or (`x || y`), but that's what's going on there.
