### ISSUE TITLE
Upgrade graceful-fs dependency to version 4

### ISSUE THREAD

**Issue by apydo** [npm/fstream#49]
Could you please upgrade your dependencies, npm states the support for graceful-fs 3 will be removed soon : 

`npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

A new version 4 of graceful-fs is available.

**Comment by othiym23** [comment]
This was done as of 53b0095290773e2e30fb1b768cdfe4db2a4baa5e, back in September / `fstream@1.0.8`. Update the version of `npm` or `fstream` that you're using? Either way, since this has been addressed, I'm going to close this issue. Thanks for your time!

**Comment by apydo** [comment]
Sorry, I missed it. This is an old dependency in unzip2. Thank you for a quick feedback.
